approvedGitRepositories:
  - "**"

enableScripts: true

nodeLinker: node-modules

packageExtensions:
  "typescript@7.0.2":
    dependencies:
      # Leaving this empty or adding standard peer dependencies
      # tells Yarn to treat it as a clean, unpatched package.
